### ISSUE TITLE
Afegir tots els sensors per la SD i Internet

### ISSUE THREAD

**Issue by yatan** [yatan/Arduino_Sensors_Sketch#15]
En cas que DO no ha obtingut dades per agitació = off --> No enviar el valor
~~Capçalera creada per Lux a SD, pero falta les dades~~
~~Les temperatures fa falta separar per upper o bottom~~

**SD :**
- [x]  Temps
- [x] Ambient
- [x]  pH
- [x] Lux
- [x]  DO

**Internet:**
- [x]  Temps
- [x] Ambient
- [x]  pH
- [x] Lux
- [x]  DO

**Comment by openspirulina** [comment]
També faltaria que es visualitzés correctament per pantalla LCD

**Comment by yatan** [comment]
https://github.com/yatan/Arduino_Sensors_Sketch/issues/15#issuecomment-401561103

Issue: https://github.com/yatan/Arduino_Sensors_Sketch/issues/16
