### ISSUE TITLE
add CO2 sensor

### ISSUE THREAD

**Issue by openspirulina** [yatan/Arduino_Sensors_Sketch#27]
Add the code to integrate this CO2 sensor: 
https://www.dfrobot.com/product-1549.html

**Comment by yatan** [comment]
https://www.dfrobot.com/wiki/index.php/Gravity:_Analog_Infrared_CO2_Sensor_For_Arduino_SKU:_SEN0219

https://www.dfrobot.com/blog-991.html

**Comment by yatan** [comment]
https://github.com/yatan/Arduino_Sensors_Sketch/commit/da86c58fdbb3cfd006c7596576121766ee9c29f6

**Comment by yatan** [comment]
Soldar pin de Digital -> Analògic

**Comment by yatan** [comment]
Per part del codi ja està llest. Només queda analitzar les dades obtingudes.
