### ISSUE TITLE
BHT1750 + Range Lux

### ISSUE THREAD

**Issue by yatan** [yatan/Arduino_Sensors_Sketch#28]
Mirar si es posible augmentar el rang de lux que pot agafar.
Permetre utilitzar mes de 2 sensors amb les mateixes adreces. (Multiplexor ? )
En principi per defecte ja agafa el màxim que són 11 bits per el UNO, potser per el mega es pot augmentar. Cal mirar-ho

**Comment by openspirulina** [comment]
No cal investigar-hi. S'utiltizarà el sensor MAX44009  per a mesurar la irradiancia del Sol.
