### ISSUE TITLE
LDR laser sequence

### ISSUE THREAD

**Issue by yatan** [yatan/Arduino_Sensors_Sketch#3]
https://github.com/yatan/Arduino_Sensors_Sketch/commit/4b2a402629285b1be12182a8295c671e252974e3#commitcomment-27492159

- mesurar tots els tancats (es pot fer sense delay),
- obrir 1, esperar, mesurar amb obert, tancar
- obrir 2, esperar, mesurar amb obert, tancar.

Ja que sinó hem d'esperar més segons cada vegada que es pren mesura del tancat...
A banda está de que cada mesura en faci 5 o 10 i faci la mitjana...

**Comment by openspirulina** [comment]
ei fran, no tinc molt clar com fer modificacions al codi, aquest bug el podria fer directament jo al codi, però no tinc molt clar com fer-ho ja que al editar-ho creo una fork...

**Comment by openspirulina** [comment]
ok jo m'ocupo de fer aquest!
