### ISSUE TITLE
Revisar Placa_23

### ISSUE THREAD

**Issue by yatan** [yatan/Arduino_Sensors_Sketch#30]
- [x] Revisar connexió interruptor cal·libració pH
- [x] Soldar CO2 al pin corresponent
- [x] Carregar nou sketch
- [x] Assignar dades BD
- [x] Verificar SD
- [x] Verificar connexió internet

**Comment by openspirulina** [comment]
caram, deunidó eehh!! jejej, no funciona la calibració, el CO2 s'havia de soldar al Analògic,..
sort que el fran ho arregla tot!!!
Te porto un SD? 
Avui trucaré en aquest noi i li dic que divendres-dilluns li enviem, te sembla?

**Comment by yatan** [comment]
@openspirulina En principi quan hagi resoldat lo que falta, la resta de checks serà cosa de 5 minutets i ja estarà llest. 
Ah, i SD ja en tinc, cap problema.
