### ISSUE TITLE
repassar funcio sort_and_filter_co2

### ISSUE THREAD

**Issue by openspirulina** [yatan/Arduino_Sensors_Sketch#33]
El co2 no hi ha manera que quadri...
s'haura de repassar loa funció sort_and_filter_co2 i aplicar uns altres filtres, per la LCD m'està mostrant un valor de 254ppm i ara he aplicar el codi del CO2 i hi han valors de 425ppm. 

Ja ho diuen als comentaris que hi han molts pics i variacions...potser si s'agafen 15 mesures s'haurien de traure les 8 de dalt i les 3 de baix.. o alguna cosa així...

https://www.dfrobot.com/product-1549.html

**Comment by openspirulina** [comment]
(he intentat treure 5 i 5 però no me'n surto...) si ho vols provar fran...

**Comment by yatan** [comment]
7c4b3e69a28eb413071eee0559e0ef537c2329c9

Agafades 25 mostres. 
Eliminades les 5 primeres i les 10 últimes. 
I de les 10 restants es fa la mitja com abans.

**Comment by openspirulina** [comment]
tanquem aquest fil ja que canviem de sensor...
