### ISSUE TITLE
afegir sensor de CO2 (MG811)

### ISSUE THREAD

**Issue by openspirulina** [yatan/Arduino_Sensors_Sketch#35]
Donat que el sensor de CO2 de dfrobot no funcoina bé, s'opta per canviar de sensor. Per el MG811. Avere què tal funciona. 

El codi amb el que està calibrat és aquest, però estaria bé, agafar unes quantes mesures, descartar màxims i mínims...
Salut!!

#define pin_sensor A1 //Pin del sensor
float adc; //Variable para obtener los valores en el 1 paso
float voltaje; //Variable para obtener el voltaje en el 2 paso
float variable; //Variable final del sensor en el 3 paso
float rel_voltaje_variable = 1; //Relación Voltaje/Variable del sensor (en el caso del LM35 es 100)
 float co2conc;
void setup()
{
  Serial.begin(9600);
}
 
void loop()
{
  //Paso 1, conversión ADC de la lectura del pin analógico
  adc = analogRead(pin_sensor);
  Serial.print(adc);
 Serial.println(" valor sensor");
  //Paso 2, obtener el voltaje
  voltaje = adc * 5 / 1023;
  Serial.print(voltaje);
 Serial.println(" V");

 co2conc=voltaje*(-3157.89)+1420;
 Serial.print(co2conc);
 Serial.println("ppm CO2");
  //Paso 3, obtener la variable de medida del sensor
  variable = voltaje * rel_voltaje_variable;
  Serial.println(variable);
 
  delay(2000);
}

**Comment by yatan** [comment]
Aprofitada la funció de #33 per ordenar, filtrar i agafar la mitja dels valors, pero amb la versió antiga de 15 mostres, i eliminant els 2 primers, i 2 últims.

Falta adaptar el fitxer de Nicolas

**Comment by yatan** [comment]
@openspirulina Actualitzat el Sketch del Nicolas.
El sensor continua estant al pin A2
